WebApplications/Pages/Marking/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ConsoleAppProject.App03;
using WebApplications.Data;
using Microsoft.EntityFrameworkCore;

namespace WebApplications.Pages.Marking
{
    public class CreateModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public CreateModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Student Student { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Student.ConvertToGrades();
            _context.Students.Add(Student);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
        /**
        public async Task<IActionResult> Analyse()
        {
            var students = await _context.Students.ToListAsync();
            StudentGrades grades = new StudentGrades();
        }
        */
    }
}

WebApplications/Pages/Marking/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ConsoleAppProject.App03;
using WebApplications.Data;

namespace WebApplications.Pages.Marking
{
    public class DeleteModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public DeleteModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Student Student { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Student = await _context.Students.FirstOrDefaultAsync(m => m.StudentId == id);

            if (Student == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Student = await _context.Students.FindAsync(id);

            if (Student != null)
            {
                _context.Students.Remove(Student);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplications/Pages/Marking/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ConsoleAppProject.App03;
using WebApplications.Data;

namespace WebApplications.Pages.Marking
{
    public class DetailsModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public DetailsModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Student Student { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Student = await _context.Students.FirstOrDefaultAsync(m => m.StudentId == id);

            if (Student == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApplications/Pages/Marking/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ConsoleAppProject.App03;
using WebApplications.Data;

namespace WebApplications.Pages.Marking
{
    public class EditModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public EditModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Student Student { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Student = await _context.Students.FirstOrDefaultAsync(m => m.StudentId == id);

            if (Student == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Student.ConvertToGrades();
            _context.Attach(Student).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StudentExists(Student.StudentId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.StudentId == id);
        }
    }
}

WebApplications/Pages/Network/Comments/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplications.Data;
using WebApplications.Pages.Network;

namespace WebApplications.Pages.Network.Comments
{
    public class CreateModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public CreateModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["PostId"] = new SelectList(_context.Posts, "PostId", "Author");
            return Page();
        }

        [BindProperty]
        public Comment Comment { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Comments.Add(Comment);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApplications/Pages/Network/Comments/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplications.Data;
using WebApplications.Pages.Network;

namespace WebApplications.Pages.Network.Comments
{
    public class DeleteModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public DeleteModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Comment Comment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Comment = await _context.Comments
                .Include(c => c.Post).FirstOrDefaultAsync(m => m.CommentId == id);

            if (Comment == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Comment = await _context.Comments.FindAsync(id);

            if (Comment != null)
            {
                _context.Comments.Remove(Comment);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApplications/Pages/Network/Comments/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplications.Data;
using WebApplications.Pages.Network;

namespace WebApplications.Pages.Network.Comments
{
    public class DetailsModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public DetailsModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Comment Comment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Comment = await _context.Comments
                .Include(c => c.Post).FirstOrDefaultAsync(m => m.CommentId == id);

            if (Comment == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApplications/Pages/Network/Comments/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplications.Data;
using WebApplications.Pages.Network;

namespace WebApplications.Pages.Network.Comments
{
    public class EditModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public EditModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Comment Comment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Comment = await _context.Comments
                .Include(c => c.Post).FirstOrDefaultAsync(m => m.CommentId == id);

            if (Comment == null)
            {
                return NotFound();
            }
           ViewData["PostId"] = new SelectList(_context.Posts, "PostId", "Author");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Comment).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CommentExists(Comment.CommentId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CommentExists(int id)
        {
            return _context.Comments.Any(e => e.CommentId == id);
        }
    }
}

WebApplications/Pages/Network/Comments/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplications.Data;
using WebApplications.Pages.Network;

namespace WebApplications.Pages.Network.Comments
{
    public class IndexModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public IndexModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Comment> Comment { get;set; }

        public async Task OnGetAsync()
        {
            Comment = await _context.Comments
                .Include(c => c.Post).ToListAsync();
        }
    }
}

WebApplications/Pages/Network/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplications.Data;
using WebApplications.Network;

namespace WebApplications.Pages.Network
{
    public class DetailsModel : PageModel
    {
        private readonly WebApplications.Data.ApplicationDbContext _context;

        public DetailsModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public MessagePost MessagePost { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            MessagePost = await _context.Messages.FirstOrDefaultAsync(m => m.PostId == id);

            if (MessagePost == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApplications/Pages/Network/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApplications.Data;
using WebApplications.Network;

namespace WebApplications.Pages.Network
{
    public class IndexModel : PageModel
    {

        private readonly WebApplications.Data.ApplicationDbContext _context;

        public IndexModel(WebApplications.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<MessagePost> MessagePost { get;set; }
        public IList<Comment> Comment { get; set; }
        public string currentSearch { get; set; }
        //public IList<PhotoPost> PhotoPost { get; set; }
        //public IList<Post> Posts { get; set; }

        public async Task OnGetAsync(string userName)
        {

            MessagePost = await _context.Messages.OrderByDescending(a => a.Timestamp).ToListAsync();
            Comment = await _context.Comments
                .Include(c => c.Post).ToListAsync();

            //PhotoPost = await _context.Photos.ToListAsync();

            //List<Post> Posts = new List<Post>();

            //Posts.AddRange(PhotoPost);
            //Posts.AddRange(MessagePost);


            //var Posts = await _context.Posts.OrderByDescending(a => a.Timestamp).ToArrayAsync();

            currentSearch = userName;

            IQueryable<MessagePost> messagesIQ = from p in _context.Messages
                                             select p;
            if (!String.IsNullOrEmpty(userName))
            {
                messagesIQ = messagesIQ.Where(p => p.Author.Contains(userName));
            }

            MessagePost = await messagesIQ.AsNoTracking().ToListAsync();
        }


        public ActionResult OnGetLike(int id)
        {
            var messagePost = _context.Messages.Find(id);

            if (messagePost == null)
            {
                return NotFound();
            }
            else
            {
                messagePost.Like();
            }

            try
            {
                _context.Update(messagePost);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                return NotFound();
            }

            return Redirect(Url.Action("Index") + $"#{id}");
        }

        public ActionResult OnGetUnLike(int id)
        {
            var messagePost = _context.Messages.Find(id);

            if (messagePost == null)
            {
                return NotFound();
            }
            else
            {
                messagePost.Unlike();
            }

            try
            {
                _context.Update(messagePost);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                return NotFound();
            }

            return Redirect(Url.Action("Index") + $"#{id}");
        }

        [BindProperty]
        public string Text { get; set; }

        public async Task<IActionResult> OnPost(int id)
        {
            Comment comment = new Comment();
            comment.Text = Text;
            comment.PostId = id;

            _context.Add(comment);
            await _context.SaveChangesAsync();

            return Redirect(Url.Action("Index") + $"#{id}");
        }
    }
}

WebApplications/Pages/Network/Create.cshtml
@page
@model WebApplications.Pages.Network.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MessagePost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MessagePost.Message" class="control-label"></label>
                <textarea asp-for="MessagePost.Message" class="form-control"></textarea>
                <span asp-validation-for="MessagePost.Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MessagePost.Author" class="control-label"></label>
                <input asp-for="MessagePost.Author" class="form-control" />
                <span asp-validation-for="MessagePost.Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplications/Pages/Network/Delete.cshtml
@page
@model WebApplications.Pages.Network.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MessagePost</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MessagePost.Message)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MessagePost.Message)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MessagePost.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MessagePost.Author)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="MessagePost.PostId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

WebApplications/Pages/Network/Details.cshtml
@page
@model WebApplications.Pages.Network.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MessagePost</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MessagePost.Message)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MessagePost.Message)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MessagePost.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MessagePost.Author)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.MessagePost.PostId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

WebApplications/Pages/Network/Edit.cshtml
@page
@model WebApplications.Pages.Network.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MessagePost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MessagePost.Message" class="control-label"></label>
                <textarea asp-for="MessagePost.Message" class="form-control"></textarea>
                <span asp-validation-for="MessagePost.Message" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="MessagePost.PostId" />
            <div class="form-group">
                <label asp-for="MessagePost.Author" class="control-label"></label>
                <input asp-for="MessagePost.Author" class="form-control" />
                <span asp-validation-for="MessagePost.Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplications/Pages/Network/Index.cshtml
@page
@model WebApplications.Pages.Network.IndexModel

@{ ViewData["Title"] = "Index"; }

<h1>Message Posts</h1>
<form asp-action="Index" method="get">
    <div class="form-action no-color">
        <p>
            Find posts by name:
            <input type="text" name="userName" value="@Model.currentSearch" />
            <input type="submit" value="Search Author" class="btn btn-info" />
            <a class="btn btn-danger" asp-action="Index"><i class="bi bi-x-circle-fill"></i> Clear Search</a>
        </p>
    </div>
</form>
<p>
    <a class="btn btn-primary float-right" asp-page="Create"><i class="bi bi-plus-circle-fill"></i> Add Message</a>
    <a class="btn btn-secondary float-right" asp-page="./Photo/Index">See Photos</a>
</p>
<br />
<br />
<div class="container col-md-8 align-self-center">
    @foreach (var item in Model.MessagePost)
    {
<div class="card bg-white" style="font-size: 2.5em; padding: 2%;">
    <div id="@item.PostId" class="card-body">
        <a asp-page="./Delete" asp-route-id="@item.PostId" class="float-right btn btn-danger"><i class="bi bi-x-circle-fill"></i> Delete Post</a>
        <h6 class="card-subtitle mb-2 text-info"><i class="bi bi-person-circle text-dark"></i> @Html.DisplayFor(modelItem => item.Author)</h6>
        <p style="font-size: 0.95em;" class="card-text">@Html.DisplayFor(modelItem => item.Message)</p>
        <div class="mt-4">
            <h6 style="font-size: 0.4em; float: left;" class="card-subtitle mb-2 text-muted">@item.FormatElapsedTime()</h6>
            <h5 style="font-size: 0.4em; float: right;" class="card-subtitle mb-2 text-muted">
                @Html.DisplayFor(modelItem => item.Likes)
                <a title="Like" asp-page-handler="Like" asp-route-id="@item.PostId" class="btn btn-outline-success"><i class="bi bi-suit-heart-fill"></i></a>
                <a title="UnLike" asp-page-handler="UnLike" asp-route-id="@item.PostId" class="btn btn-outline-danger"><i class="bi bi-heartbreak"></i></a>
            </h5>
        </div>
    </div>
</div>
                <div class="card bg-light" style="padding: 2%;">
                    <h3 class="card-title">Comments</h3>
                    @foreach (Comment comment in Model.Comment)
                    {
                        if (comment.PostId == item.PostId)
                        {
    <p>@comment.Text</p>}
}

                    <form method="post">
                        <input asp-for="@Model.Text" style="border-radius: 0.5em; border-width:0.1em; padding: 0.9%; width: 90%;" type="text" placeholder="Add a comment to this post" required />
                        <input asp-route-id="@item.PostId" type="submit" class="btn btn-primary" value="Add" />
                    </form>
                </div>
                                <br />}
</div>